name: infusion_timer
description: A new Flutter project.

publish_to: 'none'

version: 1.1.1+105

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  liquid_progress_indicator: ^0.3.2
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  android_alarm_manager_plus: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  path_provider: ^2.0.1
  package_info_plus: "^1.0.4"
  flutter_local_notifications: ^9.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - "assets/hand-bell-ringing-sound.wav"
    - "assets/icon_simple.png"
    - "assets/default_data.json"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon_simple.png"
  adaptive_icon_foreground: "assets/icon_simple_padding.png"
  adaptive_icon_background: "#009688"
