name: infusion_timer
description: "Enthusiast Tea Timer - Tea timer for Gong Fu and western style brewing for true enthusiasts."

publish_to: 'none'

version: 1.6.1+114

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  liquid_progress_indicator_v2: ^0.5.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  android_alarm_manager_plus: ^4.0.8
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.1
  package_info_plus: ^8.3.1
  flutter_local_notifications: ^19.4.0
  flutter_background: ^1.1.0
  flutter_volume_controller: ^1.3.1
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  default-flavor: default

  assets:
    - "assets/hand-bell-ringing-sound.wav"
    - "assets/icon_simple_512.png"
    - "assets/default_data.json"
